#Secret 对象类型用来保存敏感信息，
#例如密码、OAuth 令牌和 SSH 密钥。
#将这些信息放在 secret 中比放在 Pod 的定义或者 容器镜像 中来说更加安全和灵活。
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # echo -n 'admin' | base64
  username: YWRtaW4=
  #echo -n '1f2d1e2e67df' | base64
  password: MWYyZDFlMmU2N2Rm


#kubectl get secret mysecret -o jsonpath='{.data}'
#echo "aVNjITIzNDY1" | base64 --decod
  e